# -*- coding: utf-8 -*-

import requests

cookies = {
    'BDUSS': 'WdPNVBtM2w5MFFoU1pYZGY2dDBLYUtHSGZLYkNQWFR5SXBiOUxOdThxM0ctelphQVFBQUFBJCQAAAAAAAAAAAEAAAApaOAJw~zUy9TaztXK1gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMZuD1rGbg9aL'
}

req = requests.get(url="", cookies=cookies)